[project]
name = "traccia"
version = "0.1.0"
description = "Transformation & Reactive Actions Chain-based Component Integration Architecture"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
  { name = "Il Tuo Nome", email = "tu@email.com" }
]
dependencies = []